[project]
name = 'DynEscrow'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.escrow-manager]
path = 'contracts/escrow-manager.clar'
clarity_version = 3
epoch = '3.2'

[contracts.iot-tracker]
path = 'contracts/iot-tracker.clar'
clarity_version = 3
epoch = 'latest'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
