name: CI
on: [push]
jobs:
  tests:
    name: "DynEscrow"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3
      - name: "Check contract syntax"
        uses: docker://hirosystems/clarinet:latest
        with:
          args: check
